/*Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle |  | T _n_ = _n_ ( _n_ +1)/2 |  | 1, 3, 6, 10, 15, ...  
---|---|---|---|---  
Pentagonal |  | P _n_ = _n_ (3 _n_ −1)/2 |  | 1, 5, 12, 22, 35, ...  
Hexagonal |  | H _n_ = _n_ (2 _n_ −1) |  | 1, 6, 15, 28, 45, ...  
  
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <math.h>


long int getHex(long int num){
    return 2*num*num-num;
}

long int getPent(long int num){
    return num*(3*num-1)/2;
}
long int getTri(long int num){
    return num*(num+1)/2;
}

long int main(long int argc, char const *argv[]){
    //long long int a = atoi(argv[1]);
    long int tri,indHex=0,hex=0,indPent=0,pent=0,first=0;
    for(long int i = 2;; ++i){
        tri=getTri(i);
        for(;pent<tri;++indPent){
            pent=getPent(indPent);
        }
        for(;hex<tri;++indHex) {
            hex=getHex(indHex);
        }
        if(tri==pent && tri==hex){
            printf("%li %li\n", i, tri); 
            if(first) break;
            first=1;
        }
    }
    return 0;
}
    