/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

//doubly linked list for fibonacci number list
typedef struct fibLL {
    int val;
    struct fibLL *next,*prev;
} fibLL;

//gets one(the last) element of the fibList and creates the next one
int nextFib(fibLL* f){
    fibLL* fn=malloc(sizeof(fibLL));
    assert(fn && "Bad malloc");

    fn->val = f->val + f->prev->val;
    f->next=fn;
    fn->prev=f;
    return fn->val;
}

int main(int argc, char const *argv[]){
    //read Number to calc to
    int a = atoi(argv[1]);
    int sum=0;

    //setup first two numbers
    fibLL n0,n1,*ni=&n1;
    n0.val=1;  n1.val=1; 
    n0.next=&n1;n1.prev=&n0;

    int val=0;
    //calc till fibNum>a, add val 2 sum if even
    //increment list head
    while(1){
        val=nextFib(ni);
        if(val%2==0) sum+=val;
        if(val>a) break;

        ni=ni->next;
    }
    printf("%i\n", sum);

    //free all malloced items
    while(ni->val!=2){
        ni=ni->prev;
        free(ni->next);
    }
    return 0;
}